### ISSUE TITLE
warning with clojure 1.7.0alpha5

### ISSUE THREAD

**Issue by geraldodev** [funcool/buddy-core#1]
Warning: protocol #'buddy.core.mac.proto/IMac is overwriting function update
WARNING: update already refers to: #'clojure.core/update in namespace: buddy.core.mac.proto, being replaced by: #'buddy.core.mac.proto/update
Warning: protocol #'buddy.core.hash/IHash is overwriting function update
WARNING: update already refers to: #'clojure.core/update in namespace: buddy.core.hash, being replaced by: #'buddy.core.hash/update

**Comment by niwibe** [comment]
Thanks!

**Comment by niwibe** [comment]
Now released 0.4.1 with the fix ;)
