### ISSUE TITLE
AES-128 requires 32 byte key?

### ISSUE THREAD

**Issue by rahulmutt** [funcool/buddy-core#12]
AES-128 requires a 16-byte key - why is the assertion forcing the key to be 32 bytes? The encryption part of the codebase I'm working with is using Java and I want to port it to Clojure. There are already existing encryption keys that were generated to be 128-bit and are stored in a database as base64. I decoded it to a byte array and got a 16-byte key as required, but I get the following error calling crypto/decrypt:

AssertionError Assert failed: (keylength? key 32)  buddy.core.crypto/eval43723/fn--43725 (crypto.clj:415)

I used codecs/base64->str to do the decoding.

**Comment by niwinz** [comment]
You are using a high level encryption schemes, and 32 bytes key is required because 16 bytes is used for aes128 and other 16 bytes is used for hmac ;)

**Comment by rahulmutt** [comment]
I took apart the high-level encryption algorithms to just get the pure encryption w/o mac. To make my job easier I just reused the private function encrypt-cbc and decrypt-cbc in buddy.core.crypto. Would it be possible to make this public in the next version? For now I'm using them through a direct var reference.

**Comment by niwinz** [comment]
It is reasonable. I will make them public but as internal (I don't want expose them in the documentation because is "implementation detail" and I can't guaranty backward compatibility for that functions. Futhermore, I don't expect change them...)

**Comment by niwinz** [comment]
0.9.0 released with that changes and some performance improvements on that functions.
