### ISSUE TITLE
Spongycastle

### ISSUE THREAD

**Issue by benjyz** [funcool/buddy-core#13]
Bouncycastle does not work on Android. Spongycastle fixes this. "The Android platform unfortunately ships with a cut-down version of Bouncy Castle - as well as being crippled, it also makes installing an updated version of the libraries difficult due to classloader conflicts."

Should work the same way. Its widely used in production software (bitcoinJ), so should be safe to switch.

https://rtyley.github.io/spongycastle/

**Comment by niwinz** [comment]
I'm not very convinced about switching is a good idea :S 
Clojure is not widely used on android platform so at this moment it seems not high priority thing for me.
