### ISSUE TITLE
Doc still has old clojars id

### ISSUE THREAD

**Issue by rauhs** [funcool/buddy-core#16]
`[funcool/buddy-core "0.9.0"]`
 is still in the docs.

Cheers & thanks for this library! :)

**Comment by niwinz** [comment]
Hi @rauhs 

Yes, this is the correct version. Take care that "buddy" meta package has different version number that its modules ("buddy-core", "buddy-sign", ...)

In any case, thanks for your concern ;)

**Comment by rauhs** [comment]
Shouldn't it be *buddy*/buddy-core? The *funcool/boddy-core*  doesn't seem to exist (at least for v0.9.0)

**Comment by niwinz** [comment]
You are completely right! My fault! I'll fix that ASAP.

Thanks
