### ISSUE TITLE
^:deprecated to mean function deprecation, not algorithm deprecation

### ISSUE THREAD

**Issue by dottedmag** [funcool/buddy-core#22]
`^:deprecated` attribute is set on some functions, such as `buddy.core.hash/sha1`, which constitute a part of public interface of this library.

While it is useful to discourage people from using deprecated cryptographical algorithms in new code, interoperability requirements with existing systems guarantee that these functions will be used for a long time, so `^:deprecated` attribute, which ought to signify deprecation of the code, not of the algorithms, is not really warranted.

Can these attributes be removed? They get in a way when, say, `eastwood` is in use.

**Comment by niwinz** [comment]
You are right! This meta should be removed.
