### ISSUE TITLE
Documentation : missing dependency

### ISSUE THREAD

**Issue by yenda** [funcool/buddy-core#27]
I think it would be better to specify in the documentation that there is a dependency to [org.bouncycastle/bcprov-jdk15on "1.54"]

**Comment by niwinz** [comment]
I'm not clearly understand your issue. That is missing? The dependency is clearly specified in the `project.clj` https://github.com/funcool/buddy-core/blob/master/project.clj#L8

**Comment by yenda** [comment]
Sorry my bad it's probably because I use boot so I had to manually add it to my boot file.
