### ISSUE TITLE
keys.clj: read-pem->pubkey fails if read object is of type X509CertificateHolder

### ISSUE THREAD

**Issue by tmcf** [funcool/buddy-core#32]
Hi,
I'm using a public key signing certificate for with auth0 when the service is set to use public / private key pair. In this scenario the `buddy.core.keys/read-pem->pubkey` method fails as the object returned from the `PEMParser` readObject is of type: `org.bouncycastle.cert X509CertificateHolder` which the `JcaPEMKeyConverter` cannot use directly, `getSubjectPublicKeyInfo` must be called on the X509CertificateHolder first.

To support these X509 certificate public keys I use a modified read-pem->pubkey as follows:

```clojure
;; buddy/core/keys.clj
;; also add import (org.bouncycastle.cert X509CertificateHolder)
(defn- read-pem->pubkey
  [path-or-reader]
  (with-open [reader (io/reader path-or-reader)]
    (let [parser    (PEMParser. reader)
          keyinfo   (.readObject parser)
          converter (doto (JcaPEMKeyConverter.)
                      (.setProvider "BC"))]
      (if (instance? X509CertificateHolder keyinfo)
        (.getPublicKey converter (.getSubjectPublicKeyInfo keyinfo))
        (.getPublicKey converter keyinfo)))))
```

This is similar to how the `read-pem->privkey` does `instance?` checked on the object returned by the `PEMParser`.  I am happy to make a pull request for this if desired but as I am relatively unfamiliar with the buddy codebase I wanted to see if the proposed solution is stylistically compatible with buddy or the solution should be coded more like `read-pem->privkey`:

- use a `cond` instead of `if`, particularly if there are other cases to consider
- rename keyinfo to obj

Thanks. Buddy is working really well for us.

**Comment by niwinz** [comment]
Hi @tmcf 
The code snippet seems ok for me, so please make a PR!

Thanks!

**Comment by niwinz** [comment]
Fixed and released ;)
