### ISSUE TITLE
buddy-core issuing shadowing warnings with clojure 1.9

### ISSUE THREAD

**Issue by grzm** [funcool/buddy-core#34]
After updating to Clojure 1.9.0-alpha11, I've started seeing the following warning:

    WARNING: bytes? already refers to: #'clojure.core/bytes? in namespace: buddy.core.bytes, being replaced by: #'buddy.core.bytes/bytes?

https://github.com/clojure/clojure/blob/master/src/clj/clojure/core.clj#L5292-L5297

```clojure
(defn bytes?
  "Return true if x is a byte array"
  {:added "1.9"}
  [x] (if (nil? x)
        false
        (-> x class .getComponentType (= Byte/TYPE))))
```

https://github.com/funcool/buddy-core/blob/master/src/buddy/core/bytes.clj#L22-L29
```clojure
(defn bytes?
  "Test if a first parameter is a byte
  array or not."
  [x]
  (if (nil? x)
    false
    (= (Class/forName "[B")
       (.getClass x))))
```

Looks like the `clojure.core/bytes?` and `buddy.core.bytes/bytes?` are functionally equivalent.

**Comment by niwinz** [comment]
Thanks! It will be fixed for the next version.

**Comment by niwinz** [comment]
Fixed and released ;)

**Comment by grzm** [comment]
Thanks! Looking forward to the releases of buddy-sign and buddy-hashers with the updated dependencies :)

**Comment by niwinz** [comment]
buddy-sign already done, buddy-hashers still pending ;)
