### ISSUE TITLE
java.security.NoSuchAlgorithmException: PBKDF-OpenSSL SecretKeyFactory not available

### ISSUE THREAD

**Issue by elisehuard** [funcool/buddy-core#43]
Hi,  having an exception when calling buddy from oracle-java8 to decrypt a private key with a passphrase
```
2016-12-05 15:50:52,424 INFO [kixi.heimdall.handler:36] - {:msg "Something went wrong", :fn "wrap-catch-exception"}
2016-12-05 16:02:22,896 ERROR [kixi.heimdall.handler:160] - 
                                                                     java.lang.Thread.run              Thread.java:  745
                                     org.eclipse.jetty.util.thread.QueuedThreadPool$3.run    QueuedThreadPool.java:  555
                                    org.eclipse.jetty.util.thread.QueuedThreadPool.runJob    QueuedThreadPool.java:  635
                                            org.eclipse.jetty.io.AbstractConnection$2.run  AbstractConnection.java:  540
                                       org.eclipse.jetty.server.HttpConnection.onFillable      HttpConnection.java:  257
                                              org.eclipse.jetty.server.HttpChannel.handle         HttpChannel.java:  310
                                                   org.eclipse.jetty.server.Server.handle              Server.java:  497
                                   org.eclipse.jetty.server.handler.HandlerWrapper.handle      HandlerWrapper.java:   97
ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle                               
                                                      ring.adapter.jetty/proxy-handler/fn                jetty.clj:   24
                                      kixi.heimdall.components.jettyserver/wrap-config/fn          jettyserver.clj:   16
                                  kixi.heimdall.components.jettyserver/wrap-components/fn          jettyserver.clj:   10
                                                                                      ...                               
                                               ring.middleware.json/wrap-json-response/fn                 json.clj:   87
                                                 ring.middleware.json/wrap-json-params/fn                 json.clj:   72
                                    ring.middleware.keyword-params/wrap-keyword-params/fn       keyword_params.clj:   35
                                           kixi.heimdall.handler/wrap-catch-exceptions/fn              handler.clj:  158
                                              kixi.heimdall.handler/wrap-record-metric/fn              handler.clj:  133
                                           kixi.heimdall.handler/wrap-record-metric/fn/fn              handler.clj:  133
                                                kixi.heimdall.handler/wrap-escape-html/fn              handler.clj:  105
                                                                 compojure.core/routes/fn                 core.clj:  156
                                                                       clojure.core/apply                 core.clj:  659
                                                                                      ...                               
                                                                   compojure.core/routing                 core.clj:  148
                                                                   compojure.core/routing                 core.clj:  151
                                                                        clojure.core/some                 core.clj: 2674
                                                                compojure.core/routing/fn                 core.clj:  151
                                                                 compojure.core/routes/fn                 core.clj:  156
                                                                       clojure.core/apply                 core.clj:  659
                                                                                      ...                               
                                                                   compojure.core/routing                 core.clj:  148
                                                                   compojure.core/routing                 core.clj:  151
                                                                        clojure.core/some                 core.clj: 2674
                                                                compojure.core/routing/fn                 core.clj:  151
                                                              compojure.core/if-method/fn                 core.clj:   27
                                                               compojure.core/if-route/fn                 core.clj:   45
                                                        compojure.core/wrap-route-info/fn                 core.clj:  126
                                                  compojure.core/wrap-route-middleware/fn                 core.clj:  122
                                                             compojure.core/make-route/fn                 core.clj:  135
                                                                  compojure.response/fn/G             response.clj:    6
                                                                    compojure.response/fn             response.clj:   33
                                                         kixi.heimdall.handler/auth-token              handler.clj:   45
                                                  kixi.heimdall.service/create-auth-token              service.clj:   78
                                                   kixi.heimdall.service/make-token-pair!              service.clj:   58
                                                 kixi.heimdall.service/make-refresh-token              service.clj:   53
                                                        kixi.heimdall.service/private-key              service.clj:   31
                                           kixi.heimdall.service/absolute-or-resource-key              service.clj:   27
                                                     kixi.heimdall.service/private-key/fn              service.clj:   31
                                                              buddy.core.keys/private-key                 keys.clj:   96
                                                        buddy.core.keys/read-pem->privkey                 keys.clj:   60
                                                                                      ...                               
                              org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair                               
               org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt                               
                                       org.bouncycastle.openssl.jcajce.PEMUtilities.crypt                               
                                      org.bouncycastle.openssl.jcajce.PEMUtilities.getKey                                (repeats 2 times)
                  org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createSecretKeyFactory                               
                                                javax.crypto.SecretKeyFactory.getInstance    SecretKeyFactory.java:  160
                                                     javax.crypto.SecretKeyFactory.<init>    SecretKeyFactory.java:  122
java.security.NoSuchAlgorithmException: PBKDF-OpenSSL SecretKeyFactory not available
 org.bouncycastle.openssl.PEMException: Unable to create OpenSSL PBDKF: PBKDF-OpenSSL SecretKeyFactory not available
```

Code in question
```
(:require [buddy.core.keys :as ks])
...
(ks/private-key key-file (:passphrase auth-conf))
```

This started happening with the current build of Oracle java
```
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
As far as I can tell, the exact same code with same dependencies (and buddy 1.0.0 or 1.2.0) worked on an older version of Hotspot, but stopped working recently.

**Comment by elisehuard** [comment]
Solution to this: change java.security to add the Bouncycastle provider, remove the bounce ycastle jars from buddy-core, put the bouncycastle jars in jre/lib/ext
do you want a PR?  All that I've changed is removing the jars from the project.clj ... and it takes other changes to the system

**Comment by niwinz** [comment]
Hmm, I don't think that the solution is removing the jars from the dependencies. In fact you can add the bouncy castle provider without removing the jars, as it is done here: https://github.com/funcool/buddy-core/blob/master/src/buddy/core/dsa.clj#L25

I don't know why this error is happens on your environment, but it seems related to your environment/jdk configuration or something similar. If you can provide a sample private key, I'll try to create a test case for that. Without failing test case, there are no much that I can do here.

**Comment by Kah0ona** [comment]
I have a similar problem by the way, also on 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Running buddy 0.9.0

`ERROR Unable to create OpenSSL PBDKF: PBKDF-OpenSSL SecretKeyFactory not available
org.bouncycastle.openssl.PEMException: Unable to create OpenSSL PBDKF: PBKDF-OpenSSL SecretKeyFactory not available
	at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at buddy.core.keys$read_pem__GT_keypair.invokeStatic(keys.clj:54)
	at buddy.core.keys$read_pem__GT_keypair.invoke(keys.clj:41)
	at buddy.core.keys$private_key.invokeStatic(keys.clj:78)
	at buddy.core.keys$private_key.invoke(keys.clj:73)`

**Comment by jakemcc** [comment]
@elisehuard @Kah0ona Are you running into this problem when your code is running in an uberjar? If so, I've ran into the same issue. [pandect](https://github.com/xsc/pandect#uberjars-and-bouncycastle) talks about a similar problem.

pandect's solution wasn't entirely working for me, but I was able to add `:uberjar-exclusions [#"org/bouncycastle"]` to my project.clj and then change how I run my project to include the bouncycastle jars on the classpath and I no longer that that exception.

**Comment by niwinz** [comment]
Thanks @jakemcc for the tip.

The BC jars are signed, and they are known to have problems when is used in uberjar like bundles. This is because when uberjar is created all classes are packed in a big jar that already does not match the signature. And in this case JDK rejects properly add the provider. The solution that @jakemcc should work.

**Comment by niwinz** [comment]
Issue mentioned on the FAQ section of the doc: https://funcool.github.io/buddy-core/latest/#unexpected-exceptions-when-application-is-run-from-uberjar

**Comment by jameslaneconkling** [comment]
Can anyone give me a hint on how to add bouncycastle to my classpath.  I'm running

```bash
java -classpath ./bouncycastle/bcpkix-jdk15on-159.jar -jar target/uberjar/myproject-0.1.0-SNAPSHOT-standalone.jar
```

but still getting `java.lang.ClassNotFoundException` error for `org.bouncycastle.openssl.PEMParser`.  Thanks for help.

**Comment by jameslaneconkling** [comment]
@niwinz updated my first comment to clarify: I am excluding `org/bouncycastle` from my uberjar build, thus the `ClassNotFoundException`.  But the `-classpath`/`-cp` flags did not work when used w/ the `-jar` flag, as outlined in my first comment.  Adding all three artifacts (my app, and two bouncycastle jars) to the classpath and specifying the main class did work, though I don't know if there's a better way to do it.

**Comment by niwinz** [comment]
is very strange it should work as expected but for some reason in your case does not work :S

**Comment by niwinz** [comment]
please open a new issue for discuss this better, and we try to find a solution for that.

**Comment by jameslaneconkling** [comment]
@niwinz sorry for the confusion.  It does work for me now, after I stumbled upon the command in my second comment.  If you'd be open to it, I could open a PR to expand the docs.
