### ISSUE TITLE
Feature Request - Support :hmac-sha1

### ISSUE THREAD

**Issue by bpringe** [funcool/buddy-core#58]
I tried running the following but it appears there is no method implementation for `:hmac-sha1`. Will this be added?
```clojure
(mac/hash payload {:key my-secret :alg :hmac+sha1})
```
I get an exception:
```
No method in multimethod 'engine' for dispatch value: :hmac+sha1
```
And I see that the method does not exist in the source.

**Comment by shilder** [comment]
Quickest way to achieve this is to add new dispatch to multimethod, like this:

```
(defmethod mac/engine :hmac+sha1
  [options]
  (let [digest (hash/resolve-digest-engine
                 (:digest options :sha1))]
    (assert digest "Invalid digest engine.")
    (org.bouncycastle.crypto.macs.HMac. digest)))
```

But i think it can be easily added to library

**Comment by niwinz** [comment]
PR is welcome ;)

**Comment by shilder** [comment]
Sure, #59

**Comment by bpringe** [comment]
Wow, thanks for the quick responses and the PR!
