### ISSUE TITLE
Uncaught exception in buddy.core.keys causes 500 internal error when a token is invalid

### ISSUE THREAD

**Issue by theophilusx** [funcool/buddy-core#6]
Exception is org.bouncycastle.crypto.InvalidCipherTextException: checksum failed

This can occur if the token passed in cannot be decrypted. I think the fix is probaly easy, but I'm not sure how this should be reported back to the application so that you can distinguish a bad token from a filed authenticaiton. 

To reproduce this issue, you can use the jwe example.

1. query the server and get a token
2. Re-start the server. As the jwe token uses a random secret, it will generate a new secret key
3. Attempt to authenticate using the previously obtained token. As the key is now different, decryption will fail and the exception is thrown. This ends up being a 500 Internal server error. 

My setup is using immutant/undertow configuration rather than a basic ring/jetty setup, but I don't think this should make a difference. 

A possible approach would be to issue a 498 token expired/invalid error?

498 Token expired/invalid (Esri)
Returned by ArcGIS for Server. A code of 498 indicates an expired or otherwise invalid token

**Comment by niwinz** [comment]
Can you provide more details, the key and content encryption algorithms... this can be very helpful for reproduce the error.

**Comment by theophilusx** [comment]
Sure, exactly the ones used in the sample JWE app provided in the examples
directory in the repo  i.e.

(defonce secret (nonce/random-bytes 32))
(def auth-backend (jwe-backend {:secret secret
                                :options {:alg :a256kw :enc :a128gcm}
                                :unauthorized-handler
unauthorized-handler}))

If I was using a static key, then I would not have seen this error.
However, I think that is beside the point. The library needs to respond
more gracefully when it is provided invalid input, such as a token
encrypted with a different key.

On 19 September 2015 at 18:11, Andrey Antukh <notifications@github.com>
wrote:

> Can you provide more details, the key and content encryption algorithms...
> this can be very helpful for reproduce the error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/funcool/buddy-core/issues/6#issuecomment-141635084>.
>



-- 
regards,

Tim

--
Tim Cross

**Comment by niwinz** [comment]
Let's try with buddy 0.7.0, it should fix your issue.

**Comment by theophilusx** [comment]
OK, I'll give it a try and let you know

On 19 September 2015 at 19:12, Andrey Antukh <notifications@github.com>
wrote:

> Let's try with buddy 0.7.0, it should fix your issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/funcool/buddy-core/issues/6#issuecomment-141639665>.
>



-- 
regards,

Tim

--
Tim Cross

**Comment by theophilusx** [comment]
OK, upgrading to 0.7.0 seems to have fixed the issue. Sending a token which
cannot be decrypted doesn't cause a 500 error or throw an uncaught
exception.

On 19 September 2015 at 19:16, Tim Cross <theophilusx@gmail.com> wrote:

> OK, I'll give it a try and let you know
>
> On 19 September 2015 at 19:12, Andrey Antukh <notifications@github.com>
> wrote:
>
>> Let's try with buddy 0.7.0, it should fix your issue.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/funcool/buddy-core/issues/6#issuecomment-141639665>.
>>
>
>
>
> --
> regards,
>
> Tim
>
> --
> Tim Cross
>
>


-- 
regards,

Tim

--
Tim Cross

**Comment by niwinz** [comment]
Nice! Thanks for report this!
