### ISSUE TITLE
Bouncy Castle on the latest released version has a CVE of critical severity

### ISSUE THREAD

**Issue by mynomoto** [funcool/buddy-core#66]
I ran `dependency-check-maven` on the pom.xml generated by a tools.deps project using `clj -Spom`. The report attached contains the results showing evidence that several pedestal dependencies related to jetty contains high/critical severity. The report is zipped because github do not accept html attachments.
[dependency-check-report.html.zip](https://github.com/funcool/buddy-core/files/3215030/dependency-check-report.html.zip)

Current master should be fine but there is no releases after bouncy castle was updated.

**Comment by jscruggs** [comment]
This appears to be fixed in the 1.6.0 release. Looking at the code as of the 1.5.0 tag does indeed indicate that it was using org.bouncycastle/bcprov-jdk15on "1.59" but tag 1.6.0's project.clj lists org.bouncycastle/bcprov-jdk15on "1.62" as its dependency.

**Comment by mynomoto** [comment]
This is correct, closing it.
