### ISSUE TITLE
Missing base64 encoding

### ISSUE THREAD

**Issue by jumarko** [funcool/buddy-core#67]
The [buddy.core.codecs](https://github.com/funcool/buddy-core/blob/master/src/buddy/core/codecs.clj#L19) imports the `org.apache.commons.codec.binary.Base64` class but doesn't use it at all.
It would be convenient if there were `base64->bytes` and `bytes->base64` functions doing conversion from/to base65 encoded string.

Can submit a patch if there's any interest in this.

**Comment by niwinz** [comment]
The base64 codecs are in a different namespace: https://github.com/funcool/buddy-core/blob/master/src/buddy/core/codecs/base64.clj
