### ISSUE TITLE
Add support for BLAKE3

### ISSUE THREAD

**Issue by KaliszAd** [funcool/buddy-core#74]
The[ 1.69 release of Bouncy Castle](https://www.bouncycastle.org/releasenotes.html) added some BLAKE3 support. Would it be possible to add it to buddy as well? It should be much [faster](https://github.com/BLAKE3-team/BLAKE3) than the other hashing functions.

**Comment by niwinz** [comment]
Feel free to make a PR for it.

**Comment by hansenpansen** [comment]
This one could be closed, right?
