### ISSUE TITLE
Quote relevant RFC's

### ISSUE THREAD

**Issue by benjyz** [funcool/buddy-core#9]
In buddy-sign there are the relevant RFC's and drafts quoted for JWS/JWT . In terms of buddy-core  the following RFC's are relevant. Not entirely sure, perhaps could make sense to quote some of them in the documentation.

https://www.rfc-editor.org/rfc/rfc2104.txt (HMAC)
https://www.rfc-editor.org/rfc/rfc3174.txt (SHA1)
https://www.rfc-editor.org/rfc/rfc3537.txt (HMAC + DES)
https://www.rfc-editor.org/rfc/rfc4634.txt (SHA and HMAC-SHA)
https://www.rfc-editor.org/rfc/rfc4635.txt  (HMAC SHA TSIG Algorithm Identifiers)
https://www.rfc-editor.org/rfc/rfc7519.txt (JWT)
https://www.rfc-editor.org/rfc/rfc7677.txt (SASL)

**Comment by niwinz** [comment]
You are right! I will include them ASAP (tomorrow surely).

Thank you very much for the suggestion.

**Comment by niwinz** [comment]
Finally seems like I will not include that because buddy does not implement itself any chrypto algorithm and reuses from bc.

In buddy sign, in the source code are already referenced the rfcs used to implement JWE and JWS.
In any case, thanks.
